{% set name = "ttim" %}
{% set version = "0.6.7" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1751da2d111e3935c17001a37067d188ec9033d4def5f451b97264213608a206

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - lmfit >=1.0
    - matplotlib-base
    - numba >=0.5
    - numpy >=1.17
    - pandas >=1.1
    - scipy >=1.5

test:
  imports:
    - ttim

about:
  home: https://github.com/mbakker7/ttim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transient multi-layer AEM Model
  dev_url: https://github.com/mbakker7/ttim

extra:
  recipe-maintainers:
    - jentjr
    - mbakker7
    - Huite
