{% set name = "ttim" %}
{% set version = "0.7.0" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 981d7617c784bec36d30409ae6d4766303519542e8d4f1c3894f27b824352258

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - lmfit >=1.0
    - matplotlib-base
    - numba >=0.5
    - numpy >=1.17
    - pandas >=1.1
    - scipy >=1.5

test:
  imports:
    - ttim

about:
  home: https://github.com/mbakker7/ttim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transient multi-layer AEM Model
  dev_url: https://github.com/mbakker7/ttim

extra:
  recipe-maintainers:
    - dbrakenhoff
    - jentjr
    - mbakker7
    - Huite
